server:
  http2:
    enabled: false
  port: '8080'
  ssl:
    enabled: false
    key-store: '${TLS_KEYSTORE_PATH:certs/sh_keystore.jks}'
    key-store-password: '${TLS_KEYSTORE_SECRET:secret}'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true

logging:
  pattern:
    console: "%cyan(%d{HH:mm:ss.SSS}) %blue([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO